### ISSUE TITLE
File Not Found: 01 - Welcome.mp4

### ISSUE THREAD

**Issue by CapeCoralInhabitant** [ankitsejwal/Lyndor#36]
Apparently Lynda has changed something so this app no longer works. : (

I am getting....
?? Moving files inside: 00. Introduction
?? File not found: 01 - Welcome.mp4
?? File not found 02 - What you should know before watching this course.mp4
?? File not found 03 - Using the exercise files.mp4
?? File not found 04 - Moving files inside: -1. Getting Started
?? File not found 05 - and so on.......

**Comment by ankitsejwal** [comment]
Hi, @CapeCoralInhabitant thanks for reporting this issue. Did this issue occur on a course with less than 10 video files?
Can you provide the course URLs here? to reproduce the error.
Thanks

**Comment by CapeCoralInhabitant** [comment]
https://www.lynda.com/JavaScript-tutorials/Welcome/148137/158386-4.html

**Comment by ankitsejwal** [comment]
It is very important to provide the **Course URL** which in your case should be -> https://www.lynda.com/JavaScript-tutorials/JavaScript-Functions/148137-2.html
The URL you are providing is for Welcome video. It happens when you play a video(the URL changes), inorder to get back to course URL click the course name on top left corner and the course name will become the *Heading* 


![screen shot 2018-06-18 at 11 07 21 pm](https://user-images.githubusercontent.com/13817482/41537705-9a9052e2-734c-11e8-95ad-82e2f72eda4f.png)

**Comment by CapeCoralInhabitant** [comment]
Sorry for my new stupidity.  That fixed that problem.
