### ISSUE TITLE
LinkedIn Learning Support

### ISSUE THREAD

**Issue by scottyedmonds** [ankitsejwal/Lyndor#95]
Is there LinkedIn learning support? When I login through my org portal it takes me to LinkedIn Learning and not Lynda.com - the URL I get for courses is a linkedin.com/learning/ URL 

-----

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with Lyndor) :beetle: 
- [x] Feature request (request for a new functionality) :point_up:
- [x] Question :question:
- [ ] Other

### The issue was encountered on:       :computer:
- [ ] MacOS
- [x] Windows
- [x] Linux

### Login method:
- [ ] Regular login (username + password)
- [x] Organization login (cookies.txt)
- [ ] cookies.txt + Library login(for exercise file)

**Comment by ankitsejwal** [comment]
Hi @scottyedmonds it seems Lynda is finally transitioning to LinkedIn learning, there use to be a very popular repo for LinkedIn learning on Github but they striked it down on the grounds of copy-write.
I would like to ask you to look further for different solutions up there if the issue is not resolved as I have no plans to support LinkedIn learning sadly.
